{{- $fullName := include "access-manager-api.fullname" . -}}
{{-  $secretName := printf "%s-%s" $fullName "config" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "access-manager-api.labels" . | nindent 4 }}
type: Opaque
data:
    config.yaml: {{ .Values.configuration | toYaml | b64enc | quote }}