apiVersion: v1
kind: Service
metadata:
  name: {{ include "ping-atracs.fullname" . }}
  labels:
    {{- include "ping-atracs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: UDP
      name: atracs
  selector:
    {{- include "ping-atracs.selectorLabels" . | nindent 4 }}
