apiVersion: v1
kind: Service
metadata:
  name: {{ include "ping-atracs.fullname" . }}
  labels:
    {{- include "ping-atracs.labels" . | nindent 4 }}
  annotations:
    {{ .Values.service.annotations | toYaml | nindent 4 }}
spec:
  # If the service tupe is ClusterIP, the service is only accessible within the cluster
  {{- if eq .Values.service.type "ClusterIP" }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: 5000
      protocol: UDP
      name: atracs
      # Tartets
      targetPort: 5000
  selector:
    {{- include "ping-atracs.selectorLabels" . | nindent 4 }}
