{{- $fullName := include "auth-api.fullname" . -}}
{{-  $secretName := printf "%s-%s" $fullName "configs" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "auth-api.labels" . | nindent 4 }}
type: Opaque
data:
    aws.json: {{ toJson .Values.configuration.aws | indent 4 | b64enc | quote  }}
    firebase.json: {{ toJson .Values.configuration.firebase | indent 4 | b64enc | quote }}
    default.json: {{ toJson .Values.configuration.api | indent 4 | b64enc  | quote }}