{{- $fullName := include "auth-api.fullname" . -}}
{{-  $tlsSecretName := printf "%s-%s" $fullName "tls" -}}
{{- if .Values.ssl.cert -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
    name: {{ $tlsSecretName }}
    labels:
    {{- include "auth-api.labels" . | nindent 4 -}}
data:
  tls.crt: {{ .Values.ssl.cert | b64enc }}
  tls.key: {{ .Values.ssl.key  | b64enc }}
{{- end -}}