{{- $fullName := include "cdi.fullname" . -}}
{{-  $secretName := printf "%s-%s" $fullName "api-config" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "cdi.labels" . | nindent 4 }}
type: Opaque
data:
    api.yaml: {{ .Values.api.configuration | toYaml | b64enc | quote }}
    root_ca_cert.pem: {{ .Values.api.secrets.root_ca_cert_pem | b64enc | quote }}
    root_ca_key.pem: {{ .Values.api.secrets.root_ca_key_pem | b64enc | quote }}