{{- $fullName := include "notify-legacy.fullname" . -}}
{{-  $secretName := printf "%s-%s" $fullName "config" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "notify-legacy.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.configuration | toYaml | b64enc | quote }}